author: "@xlgmokha"
description: "You're looking at it."
domain: codechica.ca
lang: 'en-US'
markdown: kramdown
page_excerpts: true
title: CodeChica
url: https://codechica.ca
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "-"
      type: "pages"
    values:
      layout: "-"
  - scope:
      path: "plus-plus"
      type: "pages"
    values:
      layout: "plus-plus"
plugins:
  - jekyll-youtube
